web:
  image: nginx:alpine
  volumes:
    - './volumes:/volumes'
    - './containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
  ports:
    - '443:443'
    - '80:80'
  links:
    - python

mysql:
  environment:
    - MYSQL_ROOT_PASSWORD=passw0rd1
  image: mysql:latest
  ports:
    - '3306:3306'
    - '33060:33060'
  volumes:
    - './tmp/mysql:/var/lib/mysql'
    - './containers:/containers'
    - './volumes:/volumes'
  command:
    - '--default-authentication-plugin=mysql_native_password'

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
    - PMA_HOST=mysql
    - PMA_PORT=3306
    - UPLOAD_LIMIT=100M
  ports:
    - '8082:80'
  links:
    - mysql

python:
  build: ./containers/python/3.6/.
  volumes:
    - './volumes/app:/usr/src/myapp'
    - './volumes:/volumes'
  ports:
    - '5000:5000'
    - '5001:5001'
  expose:
    - 5000
    - 5001
  command: 'python3 /usr/src/myapp/app.py'